[tools]
"cargo:tree-sitter-cli" = "0.26.5"
node = "latest"

[tasks.lint]
quiet = true
run = "npm run lint"

[tasks.build]
quiet = true
run = '''
tree-sitter generate
tree-sitter build
'''

[tasks.test]
quiet = true
run = '''
tree-sitter generate
tree-sitter parse ./examples/sample.acc
tree-sitter query ./queries/injections.scm ./examples/sample.f90
'''
